const data = [
  {
    id: 1,
    status: 'Available',
    type: '2 Bedroom',
    state: 'Lagos',
    city: 'Ikoyi',
    address: 'Close to Shoprite',
    price: '2,000,000',
    created_on: new Date(),
    image_url: 'http://www.cloudinary.com',
    ownerEmail: 'tush@gmail.com',
    ownerPhoneNumber: '07033445566',
  },
  {
    id: 2,
    status: 'Available',
    type: 'Self-contained',
    state: 'Ogun',
    city: 'Abeokuta',
    address: '2 Oriade street, ijebu',
    price: '1,000,000',
    created_on: new Date(),
    image_url: 'http://www.cloudinary.com',
    ownerEmail: 'm@digital@gmail.com',
    ownerPhoneNumber: '08033002278',
  },
  {
    id: 3,
    status: 'Available',
    type: '3 Bedroom',
    state: 'Lagos',
    city: 'Lekki',
    address: 'Close to Shoprite',
    price: '2,000,000',
    created_on: new Date(),
    image_url: 'http://www.cloudinary.com',
    ownerEmail: 'tush@gmail.com',
    ownerPhoneNumber: '07033445566',
  },
  {
    id: 4,
    status: 'Available',
    type: '2 Bedroom',
    state: 'Ogun',
    city: 'Abeokuta',
    address: '2 Oriade street, ijebu',
    price: '12,000,000',
    created_on: new Date(),
    image_url: 'http://www.cloudinary.com',
    ownerEmail: 'm@digital@gmail.com',
    ownerPhoneNumber: '08033002278',
  },
];

export default data;
